apiVersion: v1
kind: ServiceAccount
metadata:
  name: fitness-app-sa
  namespace: fitness
  annotations:
    # This Client ID tells Workload Identity which Azure Identity to assume
    # Replace the value below with the Client ID(managed identity)
    azure.workload.identity/client-id: "83908fe5-c8f8-4957-a6a2-5c00cc77596c"
  labels:
    azure.workload.identity/use: "true"
